
inhibit_all_warnings!
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'CardManager’ do
#pod 'Yoga', :path => './../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
#
#pod 'React', :path => './../node_modules/react-native', :subspecs => [#pod的路径
#'Core',
#'RCTText',
#'RCTNetwork',
#'RCTActionSheet',
#'RCTGeolocation',
#'RCTFatal',
#'RCTImage',
##'RCTAnimation','RCTLinkingIOS',
#'RCTSettings',
#'RCTVibration',
#'RCTWebSocket',
#]

    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SVProgressHUD' , '~> 1.1.3'

end



target ‘CardManagerTests' do

end

